export const order = {
    _id: '5ea466267ac95a2aee549672',
    operatorId: null,
    status: 'pending',
    payed: false,
    storeId: '5e693b5ffd936f0013f6cc44',
    tableNum: '31',
    currency: '¥',
    content: [
        {
            delivering: 0,
            finished: 0,
            _id: '5ea466267ac95a2aee549675',
            dishSnapshot: {
                description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                soldOut: false,
                specifications: ['5e693bddfd936f0013f6cc4f'],
                __v: 5,
                date: '2020-03-11T19:26:23.359Z',
                _id: '5e693b5ffd936f0013f6cc47',
                name: '柠檬可乐－凉菜',
                price: 4,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                chef: '5e693b5ffd936f0013f6cc46',
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '',
                        multi: true,
                        __v: 4,
                        content: [
                            {
                                disable: false,
                                fare: 1,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc51',
                                name: '固定1元',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 8,
            date: '2020-04-25T16:32:38.569Z',
        },
        {
            delivering: 0,
            finished: 0,
            _id: '5ea466267ac95a2aee549674',
            dishSnapshot: {
                description: '',
                soldOut: false,
                specifications: ['5e693b5ffd936f0013f6cc49', '5e693bddfd936f0013f6cc4f'],
                __v: 2,
                date: '2020-03-11T19:27:43.221Z',
                _id: '5e693baffd936f0013f6cc4e',
                name: '可以了无需烹饪',
                price: 10,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1583954838114-T7F6fCxxGC.jpg',
                chef: null,
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '示例辣度',
                        multi: false,
                        __v: 4,
                        content: [
                            {
                                disable: false,
                                fare: 50,
                                fareType: 'percentage',
                                _id: '5e693b5ffd936f0013f6cc4c',
                                name: '特辣加价50%',
                            },
                        ],
                        date: '2020-03-11T19:26:23.407Z',
                        _id: '5e693b5ffd936f0013f6cc49',
                        name: '辣度',
                    },
                    {
                        description: '',
                        multi: true,
                        __v: 4,
                        content: [
                            {
                                disable: false,
                                fare: 1,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc51',
                                name: '固定1元',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 10,
            date: '2020-04-25T16:32:38.569Z',
        },
        {
            delivering: 0,
            finished: 0,
            _id: '5ea466267ac95a2aee549673',
            dishSnapshot: {
                description: '',
                soldOut: false,
                specifications: ['5e693bddfd936f0013f6cc4f'],
                __v: 3,
                date: '2020-03-31T04:53:04.263Z',
                _id: '5e82ccb02aa1beabadb9b906',
                name: '烤鱿鱼',
                price: 5,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1585630263616-AKfk6XTmB6.jpg',
                chef: '5e82cc3a2aa1beabadb9b905',
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '',
                        multi: true,
                        __v: 4,
                        content: [
                            {
                                disable: false,
                                fare: 1,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc51',
                                name: '固定1元',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 3,
            date: '2020-04-25T16:32:38.569Z',
        },
    ],
    clientId: '48b15940-cfc5-11e9-a6b8-f155ed6f83cc',
    tasks: [
        {
            status: 'processing',
            printed: [],
            _id: '5ea466267ac95a2aee549676',
            type: 'check',
            content: [
                {
                    _id: '5ea466267ac95a2aee549679',
                    dishSnapshot: {
                        description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                        soldOut: false,
                        specifications: ['5e693bddfd936f0013f6cc4f'],
                        __v: 5,
                        date: '2020-03-11T19:26:23.359Z',
                        _id: '5e693b5ffd936f0013f6cc47',
                        name: '柠檬可乐－凉菜',
                        price: 4,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                        chef: '5e693b5ffd936f0013f6cc46',
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '',
                                multi: true,
                                __v: 4,
                                content: [
                                    {
                                        disable: false,
                                        fare: 1,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc51',
                                        name: '固定1元',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 8,
                    date: '2020-04-25T16:32:38.571Z',
                },
                {
                    _id: '5ea466267ac95a2aee549678',
                    dishSnapshot: {
                        description: '',
                        soldOut: false,
                        specifications: ['5e693b5ffd936f0013f6cc49', '5e693bddfd936f0013f6cc4f'],
                        __v: 2,
                        date: '2020-03-11T19:27:43.221Z',
                        _id: '5e693baffd936f0013f6cc4e',
                        name: '可以了无需烹饪',
                        price: 10,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1583954838114-T7F6fCxxGC.jpg',
                        chef: null,
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '示例辣度',
                                multi: false,
                                __v: 4,
                                content: [
                                    {
                                        disable: false,
                                        fare: 50,
                                        fareType: 'percentage',
                                        _id: '5e693b5ffd936f0013f6cc4c',
                                        name: '特辣加价50%',
                                    },
                                ],
                                date: '2020-03-11T19:26:23.407Z',
                                _id: '5e693b5ffd936f0013f6cc49',
                                name: '辣度',
                            },
                            {
                                description: '',
                                multi: true,
                                __v: 4,
                                content: [
                                    {
                                        disable: false,
                                        fare: 1,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc51',
                                        name: '固定1元',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 10,
                    date: '2020-04-25T16:32:38.571Z',
                },
                {
                    _id: '5ea466267ac95a2aee549677',
                    dishSnapshot: {
                        description: '',
                        soldOut: false,
                        specifications: ['5e693bddfd936f0013f6cc4f'],
                        __v: 3,
                        date: '2020-03-31T04:53:04.263Z',
                        _id: '5e82ccb02aa1beabadb9b906',
                        name: '烤鱿鱼',
                        price: 5,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1585630263616-AKfk6XTmB6.jpg',
                        chef: '5e82cc3a2aa1beabadb9b905',
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '',
                                multi: true,
                                __v: 4,
                                content: [
                                    {
                                        disable: false,
                                        fare: 1,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc51',
                                        name: '固定1元',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 3,
                    date: '2020-04-25T16:32:38.570Z',
                },
            ],
            valet: false,
            date: '2020-04-25T16:32:38.571Z',
        },
    ],
    checkout: [],
    process: [],
    date: '2020-04-25T16:32:38.571Z',
    __v: 0,
};
export const expectPrice = 218;
