export const order = {
    _id: '5ea3d49cbb7f81e1654f812b',
    operatorId: '5e693b5ffd936f0013f6cc45',
    status: 'processing',
    payed: false,
    storeId: '5e693b5ffd936f0013f6cc44',
    tableNum: '30',
    currency: '¥',
    content: [
        {
            delivering: 0,
            finished: 0,
            _id: '5ea3d49cbb7f81e1654f812e',
            dishSnapshot: {
                description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                soldOut: false,
                specifications: ['5e693bddfd936f0013f6cc4f'],
                __v: 5,
                date: '2020-03-11T19:26:23.359Z',
                _id: '5e693b5ffd936f0013f6cc47',
                name: '柠檬可乐－凉菜',
                price: 4,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                chef: '5e693b5ffd936f0013f6cc46',
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '',
                        multi: true,
                        __v: 2,
                        content: [
                            {
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc50',
                                name: '不加价',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 1,
            date: '2020-04-25T06:11:40.385Z',
        },
        {
            delivering: 1,
            finished: 0,
            _id: '5ea3d49cbb7f81e1654f812d',
            dishSnapshot: {
                description: '',
                soldOut: false,
                specifications: ['5e693b5ffd936f0013f6cc49', '5e693bddfd936f0013f6cc4f'],
                __v: 2,
                date: '2020-03-11T19:27:43.221Z',
                _id: '5e693baffd936f0013f6cc4e',
                name: '可以了无需烹饪',
                price: 10,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1583954838114-T7F6fCxxGC.jpg',
                chef: null,
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '示例辣度',
                        multi: false,
                        __v: 1,
                        content: [
                            {
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5e693b5ffd936f0013f6cc4a',
                                name: '微辣',
                            },
                        ],
                        date: '2020-03-11T19:26:23.407Z',
                        _id: '5e693b5ffd936f0013f6cc49',
                        name: '辣度',
                    },
                    {
                        description: '',
                        multi: true,
                        __v: 2,
                        content: [
                            {
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc50',
                                name: '不加价',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 1,
            date: '2020-04-25T06:11:40.385Z',
        },
        {
            delivering: 0,
            finished: 0,
            _id: '5ea3d49cbb7f81e1654f812c',
            dishSnapshot: {
                description: '',
                soldOut: false,
                specifications: ['5e693bddfd936f0013f6cc4f'],
                __v: 3,
                date: '2020-03-31T04:53:04.263Z',
                _id: '5e82ccb02aa1beabadb9b906',
                name: '烤鱿鱼',
                price: 5,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1585630263616-AKfk6XTmB6.jpg',
                chef: '5e82cc3a2aa1beabadb9b905',
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                selectedSpecifications: [
                    {
                        description: '',
                        multi: true,
                        __v: 2,
                        content: [
                            {
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5e693bddfd936f0013f6cc50',
                                name: '不加价',
                            },
                        ],
                        date: '2020-03-11T19:28:29.273Z',
                        _id: '5e693bddfd936f0013f6cc4f',
                        name: '测试规格',
                    },
                ],
            },
            count: 1,
            date: '2020-04-25T06:11:40.385Z',
        },
    ],
    clientId: '72e35590-8476-11ea-a684-c9e2bb9ca932',
    tasks: [
        {
            status: 'finished',
            printed: [],
            _id: '5ea3d49cbb7f81e1654f812f',
            type: 'check',
            content: [
                {
                    _id: '5ea3d49cbb7f81e1654f8132',
                    dishSnapshot: {
                        description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                        soldOut: false,
                        specifications: ['5e693bddfd936f0013f6cc4f'],
                        __v: 5,
                        date: '2020-03-11T19:26:23.359Z',
                        _id: '5e693b5ffd936f0013f6cc47',
                        name: '柠檬可乐－凉菜',
                        price: 4,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                        chef: '5e693b5ffd936f0013f6cc46',
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '',
                                multi: true,
                                __v: 2,
                                content: [
                                    {
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc50',
                                        name: '不加价',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 1,
                    date: '2020-04-25T06:11:40.386Z',
                },
                {
                    _id: '5ea3d49cbb7f81e1654f8131',
                    dishSnapshot: {
                        description: '',
                        soldOut: false,
                        specifications: ['5e693b5ffd936f0013f6cc49', '5e693bddfd936f0013f6cc4f'],
                        __v: 2,
                        date: '2020-03-11T19:27:43.221Z',
                        _id: '5e693baffd936f0013f6cc4e',
                        name: '可以了无需烹饪',
                        price: 10,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1583954838114-T7F6fCxxGC.jpg',
                        chef: null,
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '示例辣度',
                                multi: false,
                                __v: 1,
                                content: [
                                    {
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5e693b5ffd936f0013f6cc4a',
                                        name: '微辣',
                                    },
                                ],
                                date: '2020-03-11T19:26:23.407Z',
                                _id: '5e693b5ffd936f0013f6cc49',
                                name: '辣度',
                            },
                            {
                                description: '',
                                multi: true,
                                __v: 2,
                                content: [
                                    {
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc50',
                                        name: '不加价',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 1,
                    date: '2020-04-25T06:11:40.386Z',
                },
                {
                    _id: '5ea3d49cbb7f81e1654f8130',
                    dishSnapshot: {
                        description: '',
                        soldOut: false,
                        specifications: ['5e693bddfd936f0013f6cc4f'],
                        __v: 3,
                        date: '2020-03-31T04:53:04.263Z',
                        _id: '5e82ccb02aa1beabadb9b906',
                        name: '烤鱿鱼',
                        price: 5,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1585630263616-AKfk6XTmB6.jpg',
                        chef: '5e82cc3a2aa1beabadb9b905',
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        selectedSpecifications: [
                            {
                                description: '',
                                multi: true,
                                __v: 2,
                                content: [
                                    {
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5e693bddfd936f0013f6cc50',
                                        name: '不加价',
                                    },
                                ],
                                date: '2020-03-11T19:28:29.273Z',
                                _id: '5e693bddfd936f0013f6cc4f',
                                name: '测试规格',
                            },
                        ],
                    },
                    count: 1,
                    date: '2020-04-25T06:11:40.385Z',
                },
            ],
            valet: true,
            date: '2020-04-25T06:11:40.386Z',
            operatorId: '5e693b5ffd936f0013f6cc45',
        },
        {
            status: 'processing',
            printed: [],
            _id: '5ea3d49cbb7f81e1654f8133',
            type: 'clean',
            date: '2020-04-25T06:11:40.446Z',
            content: [],
        },
        {
            status: 'processing',
            printed: [],
            _id: '5ea3d49cbb7f81e1654f8134',
            type: 'deliver',
            dishGroupId: '5ea3d49cbb7f81e1654f812d',
            outletNum: null,
            count: 1,
            date: '2020-04-25T06:11:40.497Z',
            content: [],
        },
    ],
    checkout: [],
    date: '2020-04-25T06:11:40.386Z',
    __v: 0,
};

export const expectPrice = 19;
