// 总价应该是23.2
export const order: any = {
    _id: '658e8a1c9efc2d00139e95e8',
    checkoutFirst: false,
    printed: [],
    printerPrinted: [],
    kdsPrinted: [],
    printStatus: 'NotPrinted',
    operatorId: null,
    salesmanId: '5fdf7107f973ec00135fa625',
    status: 'processing',
    payed: false,
    noTax: false,
    reserveTime: null,
    selfPickUp: false,
    pack: false,
    storeId: '5fdf7149f973ec00135fa626',
    tableNum: '高',
    content: [
        {
            delivering: 0,
            finished: 0,
            retreated: 0,
            _id: '658e8a1c9efc2d00139e95ec',
            dishSnapshot: {
                names: {
                    zh: '柠檬可乐(示例)',
                    en: 'Cola',
                    ug: 'لىمون كولا',
                },
                descriptions: {
                    zh: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                    en: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                    ug: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                },
                units: {
                    zh: null,
                    en: null,
                    ug: null,
                },
                type: 'Normal',
                description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                soldOut: false,
                required: true,
                specifications: ['5fdf7149f973ec00135fa628', '607ac8f75a29480013c29e98'],
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                __v: 7,
                date: '2020-12-20T15:44:09.981Z',
                _id: '5fdf7149f973ec00135fa627',
                name: '柠檬可乐(示例)',
                price: 4,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                chef: '6210c65af938d3001ae9ca7e',
                selectedSpecifications: [
                    {
                        names: {
                            zh: '辣死了',
                            en: 'spicy',
                            ug: 'ئاچچىق',
                        },
                        description: '示例辣度',
                        multi: false,
                        limit: -1,
                        __v: 10,
                        content: [
                            {
                                names: {
                                    zh: '微辣',
                                    en: 'A little',
                                    ug: 'ئازراق ئاچچىق',
                                },
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5fdf7149f973ec00135fa62b',
                                name: '微辣',
                            },
                        ],
                        date: '2020-12-20T15:44:09.987Z',
                        _id: '5fdf7149f973ec00135fa628',
                        name: '辣死了',
                    },
                ],
                noFullOrderDiscount: false,
                taxes: [
                    {
                        name: 't',
                        rate: 0.01,
                    },
                    {
                        name: '2',
                        rate: 0.05,
                    },
                ],
            },
            count: 4,
            date: '2023-12-29T08:58:04.522Z',
        },
        {
            delivering: 0,
            finished: 0,
            retreated: 0,
            _id: '658e8a1c9efc2d00139e95eb',
            dishSnapshot: {
                names: {
                    zh: '辣🌶️🌶️🌶️',
                },
                descriptions: {
                    zh: '',
                },
                units: {
                    zh: null,
                },
                type: 'Normal',
                description: '',
                soldOut: false,
                required: false,
                specifications: ['607ac8f75a29480013c29e98'],
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                __v: 7,
                date: '2021-04-16T01:21:29.215Z',
                _id: '6078e6992a20800013f0d858',
                name: '辣🌶️🌶️🌶️',
                price: 0,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/13666666666/1630298600668-e53xFFx46A.jpg',
                chef: '6210c65af938d3001ae9ca7e',
                selectedSpecifications: [
                    {
                        names: {
                            zh: '大小',
                            en: 'Size',
                            ug: 'چوڭلۇقى',
                        },
                        description: '',
                        multi: true,
                        limit: -1,
                        __v: 7,
                        content: [
                            {
                                names: {
                                    zh: '五十',
                                    en: 'Fifty',
                                    ug: 'خىيالىڭىز يوق',
                                },
                                disable: false,
                                fare: 50,
                                fareType: 'fixed',
                                _id: '607ac8f75a29480013c29e99',
                                name: 'خىيالىڭىز يوق',
                            },
                        ],
                        date: '2021-04-17T11:39:35.523Z',
                        _id: '607ac8f75a29480013c29e98',
                        name: 'چوڭلۇقى',
                    },
                ],
                noFullOrderDiscount: false,
                taxes: [
                    {
                        name: 't',
                        rate: 0.01,
                    },
                    {
                        name: '2',
                        rate: 0.05,
                    },
                ],
            },
            count: 2,
            date: '2023-12-29T08:58:04.522Z',
        },
        {
            delivering: 0,
            finished: 0,
            retreated: 0,
            _id: '658e8a1c9efc2d00139e95ea',
            dishSnapshot: {
                names: {
                    zh: '必点',
                    en: 'Must have very lang lang lang lang lang lang lang',
                    ug: 'زاكاز قىلىش كېرەك',
                },
                descriptions: {
                    zh: '',
                    en: '',
                    ug: '',
                },
                units: {
                    zh: null,
                    en: null,
                    ug: null,
                },
                type: 'Normal',
                description: '',
                soldOut: false,
                required: false,
                specifications: ['5fdf7149f973ec00135fa628', '607ac8f75a29480013c29e98'],
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                __v: 7,
                date: '2021-07-21T05:55:09.530Z',
                _id: '60f7b6bd772a88001381cea5',
                name: '必点',
                price: 2,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/13666666666/1667015162752-e65Gwz8JhF.jpg',
                chef: '6210c65af938d3001ae9ca7e',
                selectedSpecifications: [
                    {
                        names: {
                            zh: '辣死了',
                            en: 'spicy',
                            ug: 'ئاچچىق',
                        },
                        description: '示例辣度',
                        multi: false,
                        limit: -1,
                        __v: 10,
                        content: [
                            {
                                names: {
                                    zh: '微辣',
                                    en: 'A little',
                                    ug: 'ئازراق ئاچچىق',
                                },
                                disable: false,
                                fare: 0,
                                fareType: 'fixed',
                                _id: '5fdf7149f973ec00135fa62b',
                                name: '微辣',
                            },
                        ],
                        date: '2020-12-20T15:44:09.987Z',
                        _id: '5fdf7149f973ec00135fa628',
                        name: '辣死了',
                    },
                ],
                noFullOrderDiscount: false,
                taxes: [
                    {
                        name: 't',
                        rate: 0.01,
                    },
                    {
                        name: '2',
                        rate: 0.05,
                    },
                ],
            },
            count: 2,
            date: '2023-12-29T08:58:04.522Z',
        },
        {
            delivering: 0,
            finished: 0,
            retreated: 0,
            _id: '658e8a1c9efc2d00139e95e9',
            dishSnapshot: {
                names: {
                    zh: '1',
                },
                descriptions: {
                    zh: '',
                },
                type: 'Normal',
                description: '',
                soldOut: false,
                required: false,
                specifications: [],
                salesType: ['dine', 'takeout'],
                takeoutPrice: null,
                __v: 0,
                date: '2021-09-20T12:51:21.885Z',
                _id: '614883c94abbba00136ccb15',
                name: '1',
                price: 1,
                img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1592144190779-QRTrDtCm2n.jpg',
                chef: '6210c65af938d3001ae9ca7e',
                selectedSpecifications: [],
                noFullOrderDiscount: false,
                taxes: [
                    {
                        name: 't',
                        rate: 0.01,
                    },
                    {
                        name: '2',
                        rate: 0.05,
                    },
                ],
            },
            count: 10,
            date: '2023-12-29T08:58:04.521Z',
        },
    ],
    clientId: '5fdf7107f973ec00135fa625',
    adultNum: 1,
    childNum: 1,
    type: 'buffet',
    tasks: [
        {
            status: 'finished',
            printed: [],
            printerPrinted: [],
            kdsPrinted: [],
            printStatus: 'Completed',
            _id: '658e8a1c9efc2d00139e95ed',
            type: 'check',
            content: [
                {
                    delivering: 0,
                    retreated: 0,
                    _id: '658e8a1c9efc2d00139e95f1',
                    dishSnapshot: {
                        names: {
                            zh: '柠檬可乐(示例)',
                            en: 'Cola',
                            ug: 'لىمون كولا',
                        },
                        descriptions: {
                            zh: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                            en: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                            ug: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                        },
                        units: {
                            zh: null,
                            en: null,
                            ug: null,
                        },
                        type: 'Normal',
                        description: '冰爽可乐添加新鲜柠檬片，提神醒脑，让您胃口大开～',
                        soldOut: false,
                        required: true,
                        specifications: ['5fdf7149f973ec00135fa628', '607ac8f75a29480013c29e98'],
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        __v: 7,
                        date: '2020-12-20T15:44:09.981Z',
                        _id: '5fdf7149f973ec00135fa627',
                        name: '柠檬可乐(示例)',
                        price: 4,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1574590762349-BpEiDmAWpf.jpg',
                        chef: '6210c65af938d3001ae9ca7e',
                        selectedSpecifications: [
                            {
                                names: {
                                    zh: '辣死了',
                                    en: 'spicy',
                                    ug: 'ئاچچىق',
                                },
                                description: '示例辣度',
                                multi: false,
                                limit: -1,
                                __v: 10,
                                content: [
                                    {
                                        names: {
                                            zh: '微辣',
                                            en: 'A little',
                                            ug: 'ئازراق ئاچچىق',
                                        },
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5fdf7149f973ec00135fa62b',
                                        name: '微辣',
                                    },
                                ],
                                date: '2020-12-20T15:44:09.987Z',
                                _id: '5fdf7149f973ec00135fa628',
                                name: '辣死了',
                            },
                        ],
                        noFullOrderDiscount: false,
                        taxes: [
                            {
                                name: 't',
                                rate: 0.01,
                            },
                            {
                                name: '2',
                                rate: 0.05,
                            },
                        ],
                    },
                    count: 4,
                    date: '2023-12-29T08:58:04.523Z',
                },
                {
                    delivering: 0,
                    retreated: 0,
                    _id: '658e8a1c9efc2d00139e95f0',
                    dishSnapshot: {
                        names: {
                            zh: '辣🌶️🌶️🌶️',
                        },
                        descriptions: {
                            zh: '',
                        },
                        units: {
                            zh: null,
                        },
                        type: 'Normal',
                        description: '',
                        soldOut: false,
                        required: false,
                        specifications: ['607ac8f75a29480013c29e98'],
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        __v: 7,
                        date: '2021-04-16T01:21:29.215Z',
                        _id: '6078e6992a20800013f0d858',
                        name: '辣🌶️🌶️🌶️',
                        price: 0,
                        img:
                            'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/13666666666/1630298600668-e53xFFx46A.jpg',
                        chef: '6210c65af938d3001ae9ca7e',
                        selectedSpecifications: [
                            {
                                names: {
                                    zh: '大小',
                                    en: 'Size',
                                    ug: 'چوڭلۇقى',
                                },
                                description: '',
                                multi: true,
                                limit: -1,
                                __v: 7,
                                content: [
                                    {
                                        names: {
                                            zh: '五十',
                                            en: 'Fifty',
                                            ug: 'خىيالىڭىز يوق',
                                        },
                                        disable: false,
                                        fare: 50,
                                        fareType: 'fixed',
                                        _id: '607ac8f75a29480013c29e99',
                                        name: 'خىيالىڭىز يوق',
                                    },
                                ],
                                date: '2021-04-17T11:39:35.523Z',
                                _id: '607ac8f75a29480013c29e98',
                                name: 'چوڭلۇقى',
                            },
                        ],
                        noFullOrderDiscount: false,
                        taxes: [
                            {
                                name: 't',
                                rate: 0.01,
                            },
                            {
                                name: '2',
                                rate: 0.05,
                            },
                        ],
                    },
                    count: 2,
                    date: '2023-12-29T08:58:04.523Z',
                },
                {
                    delivering: 0,
                    retreated: 0,
                    _id: '658e8a1c9efc2d00139e95ef',
                    dishSnapshot: {
                        names: {
                            zh: '必点',
                            en: 'Must have very lang lang lang lang lang lang lang',
                            ug: 'زاكاز قىلىش كېرەك',
                        },
                        descriptions: {
                            zh: '',
                            en: '',
                            ug: '',
                        },
                        units: {
                            zh: null,
                            en: null,
                            ug: null,
                        },
                        type: 'Normal',
                        description: '',
                        soldOut: false,
                        required: false,
                        specifications: ['5fdf7149f973ec00135fa628', '607ac8f75a29480013c29e98'],
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        __v: 7,
                        date: '2021-07-21T05:55:09.530Z',
                        _id: '60f7b6bd772a88001381cea5',
                        name: '必点',
                        price: 2,
                        img:
                            'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/13666666666/1667015162752-e65Gwz8JhF.jpg',
                        chef: '6210c65af938d3001ae9ca7e',
                        selectedSpecifications: [
                            {
                                names: {
                                    zh: '辣死了',
                                    en: 'spicy',
                                    ug: 'ئاچچىق',
                                },
                                description: '示例辣度',
                                multi: false,
                                limit: -1,
                                __v: 10,
                                content: [
                                    {
                                        names: {
                                            zh: '微辣',
                                            en: 'A little',
                                            ug: 'ئازراق ئاچچىق',
                                        },
                                        disable: false,
                                        fare: 0,
                                        fareType: 'fixed',
                                        _id: '5fdf7149f973ec00135fa62b',
                                        name: '微辣',
                                    },
                                ],
                                date: '2020-12-20T15:44:09.987Z',
                                _id: '5fdf7149f973ec00135fa628',
                                name: '辣死了',
                            },
                        ],
                        noFullOrderDiscount: false,
                        taxes: [
                            {
                                name: 't',
                                rate: 0.01,
                            },
                            {
                                name: '2',
                                rate: 0.05,
                            },
                        ],
                    },
                    count: 2,
                    date: '2023-12-29T08:58:04.523Z',
                },
                {
                    delivering: 0,
                    retreated: 0,
                    _id: '658e8a1c9efc2d00139e95ee',
                    dishSnapshot: {
                        names: {
                            zh: '1',
                        },
                        descriptions: {
                            zh: '',
                        },
                        type: 'Normal',
                        description: '',
                        soldOut: false,
                        required: false,
                        specifications: [],
                        salesType: ['dine', 'takeout'],
                        takeoutPrice: null,
                        __v: 0,
                        date: '2021-09-20T12:51:21.885Z',
                        _id: '614883c94abbba00136ccb15',
                        name: '1',
                        price: 1,
                        img: 'https://feige-img-hub.oss-cn-hangzhou.aliyuncs.com/1592144190779-QRTrDtCm2n.jpg',
                        chef: '6210c65af938d3001ae9ca7e',
                        selectedSpecifications: [],
                        noFullOrderDiscount: false,
                        taxes: [
                            {
                                name: 't',
                                rate: 0.01,
                            },
                            {
                                name: '2',
                                rate: 0.05,
                            },
                        ],
                    },
                    count: 10,
                    date: '2023-12-29T08:58:04.523Z',
                },
            ],
            valet: true,
            date: '2023-12-29T08:58:04.524Z',
            operatorId: '5fdf7107f973ec00135fa625',
        },
        {
            status: 'processing',
            printed: [],
            printerPrinted: [],
            kdsPrinted: [],
            printStatus: 'NotPrinted',
            _id: '658e8a1c9efc2d00139e95f4',
            type: 'clean',
            date: '2023-12-29T08:58:04.555Z',
            content: [],
        },
    ],
    taxType: 'priceNoTaxBindDish',
    priceHaveTaxBindOrderTaxes: [],
    autoCleanTime: '2023-12-29T09:03:04.512Z',
    serialOrderId: '20231229-1',
    buffet: {
        snapshot: {
            names: {
                zh: '1',
            },
            price: {
                adult: 10,
                child: 5,
            },
            dishes: [
                {
                    upperLimit: {
                        enable: true,
                        adult: 1,
                        child: 1,
                    },
                    _id: '658e89db9efc2d00139e95e5',
                    dishId: '5fdf7149f973ec00135fa627',
                },
                {
                    upperLimit: {
                        enable: true,
                        adult: 1,
                        child: 1,
                    },
                    _id: '658e89db9efc2d00139e95e4',
                    dishId: '60f7b6bd772a88001381cea5',
                },
                {
                    upperLimit: {
                        enable: false,
                        adult: 1,
                        child: 1,
                    },
                    _id: '658e89db9efc2d00139e95e3',
                    dishId: '614883c94abbba00136ccb15',
                },
            ],
            _id: '658e89209efc2d00139e95d8',
        },
        taxes: [
            {
                _id: '658e8a1c9efc2d00139e95f3',
                name: 't',
                rate: 0.01,
            },
            {
                _id: '658e8a1c9efc2d00139e95f2',
                name: '2',
                rate: 0.05,
            },
        ],
    },
    checkout: [],
    process: [],
    taxes: [],
    date: '2023-12-29T08:58:04.525Z',
    __v: 0,
};
export const expectPrice = 123;
